import { createHash } from "node:crypto";
import type { AuthorizedPrincipal } from "@shelfops/application/authorization/authorized-principal";
import { RecurrenceDecisionIdempotencyConflictError, RecurrenceDecisionValidationError, assertRecurrenceDecisionAuthorization, prepareRecurrenceDecision, type RecurrenceDecisionExecutor, type RecurrenceDecisionInput, type RecurrenceDecisionOutcome, type RecurrenceDecisionReceipt } from "@shelfops/application/recurrence/authority";
import { v7 } from "uuid";
import type { SqlClient } from "../reference-data/postgres-configuration-repository.js";

interface TransactionClient extends SqlClient { release(error?: Error | boolean): void; }
export interface RecurrenceAuthorityTransactionPool { connect(): Promise<TransactionClient>; }
type SuggestionRow = { organization_id: string; incident_id: string; candidate_incident_id: string; store_id: string; sector_id: string; category_key: string; reporter_user_id: string; candidate_store_id: string; candidate_sector_id: string; candidate_category_key: string; candidate_reporter_user_id: string; };
const digest = (value: unknown) => createHash("sha256").update(JSON.stringify(value)).digest("hex");
const lockKey = (principalId: string, sourceSuggestionId: string, key: string) => createHash("sha256").update(JSON.stringify([principalId, "v1", "recurrence-decision", sourceSuggestionId, key])).digest().readBigInt64BE(0).toString();
const fingerprint = (input: RecurrenceDecisionInput) => digest([input.sourceSuggestionId, input.state, input.expectedVersion, input.note?.trim() ?? null, input.correctionReason?.trim() ?? null]);

export class PostgresRecurrenceAuthorityExecutor implements RecurrenceDecisionExecutor {
  constructor(private readonly pool: RecurrenceAuthorityTransactionPool, private readonly id = () => v7()) {}
  async execute(principal: AuthorizedPrincipal, input: RecurrenceDecisionInput): Promise<RecurrenceDecisionOutcome> {
    const client = await this.pool.connect(); try { await client.query("BEGIN"); } catch (error) { client.release(error instanceof Error ? error : true); throw error; }
    let outcome: RecurrenceDecisionReceipt;
    try {
      const command = prepareRecurrenceDecision(principal, input); const actor = (await client.query<{ organization_id: string }>("SELECT organization_id FROM users WHERE id=$1 AND active", [command.actorId])).rows[0]; if (!actor) throw new Error("forbidden");
      const suggestion = (await client.query<SuggestionRow>("SELECT s.organization_id,s.incident_id,s.candidate_incident_id,i.store_id,i.sector_id,i.category_key,i.reporter_user_id,c.store_id candidate_store_id,c.sector_id candidate_sector_id,c.category_key candidate_category_key,c.reporter_user_id candidate_reporter_user_id FROM recurrence_suggestions s JOIN incidents i ON i.id=s.incident_id AND i.organization_id=s.organization_id JOIN incidents c ON c.id=s.candidate_incident_id AND c.organization_id=s.organization_id WHERE s.id=$1 AND s.organization_id=$2", [command.sourceSuggestionId, actor.organization_id])).rows[0]; if (!suggestion) throw new Error("not-found");
      assertRecurrenceDecisionAuthorization(principal, { id: suggestion.incident_id, storeId: suggestion.store_id, sectorId: suggestion.sector_id, category: suggestion.category_key, reporterId: suggestion.reporter_user_id }, { id: suggestion.candidate_incident_id, storeId: suggestion.candidate_store_id, sectorId: suggestion.candidate_sector_id, category: suggestion.candidate_category_key, reporterId: suggestion.candidate_reporter_user_id }, command.state);
      await client.query("SELECT pg_advisory_xact_lock($1::bigint)", [lockKey(principal.id, command.sourceSuggestionId, command.idempotencyKey)]); const current = (await client.query<{ version: number }>("SELECT version FROM incidents WHERE id=$1 AND organization_id=$2 FOR UPDATE", [suggestion.incident_id, actor.organization_id])).rows[0]; if (!current) throw new Error("not-found");
      const hash = fingerprint(command); const previous = (await client.query<{ request_hash: string; outcome: RecurrenceDecisionReceipt }>("SELECT request_hash,outcome FROM incident_creation_idempotency WHERE principal_id=$1 AND api_major='v1' AND operation='recurrence-decision' AND key=$2", [principal.id, command.idempotencyKey])).rows[0];
      if (previous) { if (previous.request_hash !== hash) throw new RecurrenceDecisionIdempotencyConflictError(); outcome = previous.outcome; } else {
        if (current.version !== command.expectedVersion) throw new Error("stale-version"); const predecessor = (await client.query<{ sequence: number }>("SELECT sequence FROM recurrence_decisions WHERE suggestion_id=$1 AND organization_id=$2 ORDER BY sequence DESC LIMIT 1", [command.sourceSuggestionId, actor.organization_id])).rows[0]; const sequence = (predecessor?.sequence ?? 0) + 1;
        if (sequence === 1 && command.correctionReason !== undefined || sequence > 1 && command.correctionReason === undefined) throw new RecurrenceDecisionValidationError();
        const decisionId = this.id(); const decided = await client.query<{ decided_at: Date }>("INSERT INTO recurrence_decisions(id,organization_id,suggestion_id,sequence,state,actor_user_id,note,correction_reason,predecessor_sequence,correlation_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING decided_at", [decisionId, actor.organization_id, command.sourceSuggestionId, sequence, command.state, command.actorId, command.note ?? null, command.correctionReason ?? null, predecessor?.sequence ?? null, command.correlationId]);
        if (command.state === "confirmed") await client.query("INSERT INTO recurrence_links(id,organization_id,suggestion_id,confirmed_decision_id) VALUES($1,$2,$3,$4) ON CONFLICT (suggestion_id) DO NOTHING", [this.id(), actor.organization_id, command.sourceSuggestionId, decisionId]);
        const event = await client.query<{ sequence: number }>("SELECT COALESCE(MAX(sequence),0)+1 sequence FROM incident_events WHERE incident_id=$1", [suggestion.incident_id]); await client.query("INSERT INTO incident_events(id,incident_id,sequence,event_type,actor_user_id,origin,data) VALUES($1,$2,$3,'recurrence-decision',$4,'human',jsonb_strip_nulls(jsonb_build_object('sourceSuggestionId',$5::text,'decisionId',$6::text,'state',$7::text,'sequence',$8::integer,'predecessorSequence',$9::integer,'correlationId',$10::text,'note',$11::text,'correctionReason',$12::text)))", [this.id(), suggestion.incident_id, event.rows[0]!.sequence, command.actorId, command.sourceSuggestionId, decisionId, command.state, sequence, predecessor?.sequence ?? null, command.correlationId, command.note ?? null, command.correctionReason ?? null]);
        const version = (await client.query<{ version: number }>("UPDATE incidents SET version=version+1,updated_at=transaction_timestamp() WHERE id=$1 AND organization_id=$2 RETURNING version", [suggestion.incident_id, actor.organization_id])).rows[0]!.version; outcome = { status: "decided", sourceSuggestionId: command.sourceSuggestionId, decisionId, state: command.state, sequence, ...(predecessor ? { predecessorSequence: predecessor.sequence } : {}), incidentId: suggestion.incident_id, version, decidedAt: decided.rows[0]!.decided_at.toISOString() };
        await client.query("INSERT INTO incident_creation_idempotency(principal_id,api_major,operation,key,request_hash,outcome) VALUES($1,'v1','recurrence-decision',$2,$3,$4)", [principal.id, command.idempotencyKey, hash, outcome]);
      }
    } catch (error) { try { await client.query("ROLLBACK"); } catch {} client.release(); throw error; }
    try { await client.query("COMMIT"); } catch { client.release(true); return { status: "indeterminate", correlationId: input.correlationId, retryWithSameKey: true }; }
    client.release(); return outcome;
  }
}
