import { readFile } from "node:fs/promises";
import { PostgreSqlContainer } from "@testcontainers/postgresql";
import type { AuthorizedPrincipal } from "@shelfops/application/authorization/authorized-principal";
import { RecurrenceDecisionIdempotencyConflictError, RecurrenceDecisionValidationError, type RecurrenceDecisionInput } from "@shelfops/application/recurrence/authority";
import { Pool } from "pg";
import { describe, expect, it } from "vitest";
import { PostgresRecurrenceAuthorityExecutor, type RecurrenceAuthorityTransactionPool } from "../src/recurrence/postgres-recurrence-authority-executor.js";

const image = "postgres:16.10-alpine@sha256:029660641a0cfc575b14f336ba448fb8a75fd595d42e1fa316b9fb4378742297";
const id = (value: number) => `00000000-0000-7000-8000-${String(value).padStart(12, "0")}`;
const ids = { organization: id(1), store: id(3), sector: id(4), location: id(5), hiddenStore: id(6), hiddenSector: id(7), hiddenLocation: id(8), actor: id(9), viewer: id(10), candidateUser: id(11), owner: id(12), candidate: id(13), hidden: id(14), suggestion: id(15), dismissed: id(16), concurrentOwner: id(17), concurrentCandidate: id(18), concurrent: id(19), rollbackOwner: id(20), rollbackCandidate: id(21), rollback: id(22) };
const principal = (userId = ids.actor): AuthorizedPrincipal => ({ id: userId, active: true, roleScopes: [{ role: "collaborator", storeIds: [ids.store], sectorIds: [ids.sector], categoryResponsibilities: [], teamIds: [] }], grants: [] });
const input = (sourceSuggestionId: string, overrides: Partial<RecurrenceDecisionInput> = {}): RecurrenceDecisionInput => ({ sourceSuggestionId, state: "confirmed", expectedVersion: 1, idempotencyKey: `decision-${sourceSuggestionId}`, correlationId: "request-correlation", note: "reviewed", ...overrides });

function lostCommit(pool: Pool): RecurrenceAuthorityTransactionPool { return { connect: async () => { const client = await pool.connect(); return { query: async <Row extends Record<string, unknown>>(sql: string, values?: readonly unknown[]) => { if (sql === "COMMIT") { await client.query("COMMIT"); throw new Error("acknowledgement lost"); } return values === undefined ? client.query<Row>(sql) : client.query<Row>(sql, [...values]); }, release: (error?: Error | boolean) => client.release(error) }; } }; }

describe("PostgreSQL recurrence decision authority", () => {
  it("keeps human decisions authorized, append-only, idempotent, atomic, and recoverable", async () => {
    const container = await new PostgreSqlContainer(image).withDatabase("recurrence_authority").start(); const pool = new Pool({ connectionString: container.getConnectionUri() });
    const insertIncident = async (incidentId: string, reporterId: string, storeId = ids.store, sectorId = ids.sector, locationId = ids.location) => pool.query("INSERT INTO incidents(id,organization_id,store_id,sector_id,location_id,category_key,severity_key,title,description,occurred_at,reporter_user_id) VALUES($1,$2,$3,$4,$5,'equipment-failure','low','Incident','Incident',transaction_timestamp(),$6)", [incidentId, ids.organization, storeId, sectorId, locationId, reporterId]);
    const insertSuggestion = async (suggestionId: string, incidentId: string, candidateId: string, occurrence = 1) => pool.query("INSERT INTO recurrence_suggestions(id,organization_id,incident_id,candidate_incident_id,recurrence_rule_version_id,occurrence,matching_facts,correlation_id) VALUES($1,$2,$3,$4,$5,$6,jsonb_build_object('locationId',$7::text),$8)", [suggestionId, ids.organization, incidentId, candidateId, id(2), occurrence, ids.location, `evaluation-${occurrence}`]);
    const state = async (suggestionId: string) => (await pool.query<{ state: string; decision_sequence: number | null }>("SELECT state,decision_sequence FROM current_recurrence_suggestion_states WHERE suggestion_id=$1", [suggestionId])).rows[0]!;
    const counts = async (suggestionId: string) => (await pool.query<{ decisions: number; links: number; events: number; version: number }>("SELECT (SELECT count(*) FROM recurrence_decisions WHERE suggestion_id=$1)::int decisions,(SELECT count(*) FROM recurrence_links WHERE suggestion_id=$1)::int links,(SELECT count(*) FROM incident_events e JOIN recurrence_suggestions x ON x.incident_id=e.incident_id WHERE x.id=$1 AND e.data->>'sourceSuggestionId'=x.id::text)::int events,(SELECT i.version FROM incidents i JOIN recurrence_suggestions x ON x.incident_id=i.id WHERE x.id=$1) version", [suggestionId])).rows[0]!;
    try {
      for (const migration of ["001_reference-data.sql", "005_incidents-core.sql", "006_team-assignments.sql", "007_incident-creation.sql", "008_sla-policy-and-cycles.sql", "009_sla-policy-configuration.sql", "010_recurrence-authority.sql"]) await pool.query(await readFile(`migrations/${migration}`, "utf8"));
      await pool.query("INSERT INTO stores(id,organization_id,name) VALUES($1,$2,'A'),($3,$2,'B')", [ids.store, ids.organization, ids.hiddenStore]); await pool.query("INSERT INTO sectors(id,organization_id,store_id,name) VALUES($1,$2,$3,'A'),($4,$2,$5,'B')", [ids.sector, ids.organization, ids.store, ids.hiddenSector, ids.hiddenStore]); await pool.query("INSERT INTO locations(id,organization_id,store_id,sector_id,name) VALUES($1,$2,$3,$4,'A'),($5,$2,$6,$7,'B')", [ids.location, ids.organization, ids.store, ids.sector, ids.hiddenLocation, ids.hiddenStore, ids.hiddenSector]); await pool.query("INSERT INTO users(id,organization_id,name) VALUES($1,$2,'Actor'),($3,$2,'Viewer'),($4,$2,'Candidate')", [ids.actor, ids.organization, ids.viewer, ids.candidateUser]);
      for (const [incidentId, reporterId, storeId, sectorId, locationId] of [[ids.owner, ids.actor, ids.store, ids.sector, ids.location], [ids.candidate, ids.candidateUser, ids.store, ids.sector, ids.location], [ids.hidden, ids.candidateUser, ids.hiddenStore, ids.hiddenSector, ids.hiddenLocation], [ids.concurrentOwner, ids.actor, ids.store, ids.sector, ids.location], [ids.concurrentCandidate, ids.candidateUser, ids.store, ids.sector, ids.location], [ids.rollbackOwner, ids.actor, ids.store, ids.sector, ids.location], [ids.rollbackCandidate, ids.candidateUser, ids.store, ids.sector, ids.location]] as const) await insertIncident(incidentId, reporterId, storeId, sectorId, locationId);
      await insertSuggestion(ids.suggestion, ids.owner, ids.candidate); await insertSuggestion(ids.dismissed, ids.owner, ids.candidate, 2); await insertSuggestion(ids.concurrent, ids.concurrentOwner, ids.concurrentCandidate); await insertSuggestion(ids.rollback, ids.rollbackOwner, ids.rollbackCandidate); await insertSuggestion(id(23), ids.owner, ids.hidden, 3);
      const executor = new PostgresRecurrenceAuthorityExecutor(pool); expect(await state(ids.suggestion)).toEqual({ state: "pending", decision_sequence: null });
      const confirmed = await executor.execute(principal(), input(ids.suggestion)); expect(confirmed).toMatchObject({ status: "decided", sourceSuggestionId: ids.suggestion, state: "confirmed", sequence: 1, incidentId: ids.owner, version: 2 }); expect(await executor.execute(principal(), input(ids.suggestion))).toEqual(confirmed); expect(await executor.execute(principal(), input(ids.suggestion, { note: " reviewed " }))).toEqual(confirmed); expect(await counts(ids.suggestion)).toEqual({ decisions: 1, links: 1, events: 1, version: 2 }); expect((await pool.query<{ version: number; state: string }>("SELECT version,state FROM incidents WHERE id=$1", [ids.candidate])).rows).toEqual([{ version: 1, state: "open" }]);
      if (confirmed.status !== "decided") throw new Error("expected decided outcome"); const provenance = await pool.query<{ actor: string; note: string; correlation: string; origin: string; source: string }>("SELECT d.actor_user_id::text actor,d.note,d.correlation_id correlation,e.origin,e.data->>'sourceSuggestionId' source FROM recurrence_decisions d JOIN recurrence_suggestions s ON s.id=d.suggestion_id JOIN incident_events e ON e.incident_id=s.incident_id AND e.data->>'decisionId'=d.id::text WHERE d.id=$1", [confirmed.decisionId]); expect(provenance.rows).toEqual([{ actor: ids.actor, note: "reviewed", correlation: "request-correlation", origin: "human", source: ids.suggestion }]);
      await expect(executor.execute(principal(), input(ids.suggestion, { state: "dismissed" }))).rejects.toThrow(RecurrenceDecisionIdempotencyConflictError); await expect(executor.execute(principal(), input(ids.suggestion, { expectedVersion: 1, idempotencyKey: "stale", state: "dismissed", correctionReason: "stale correction" }))).rejects.toThrow("stale-version");
      const dismissed = await executor.execute(principal(), input(ids.dismissed, { expectedVersion: 2, state: "dismissed", idempotencyKey: "dismiss-only" })); expect(dismissed).toMatchObject({ status: "decided", sequence: 1, version: 3 }); expect(await state(ids.dismissed)).toMatchObject({ state: "dismissed", decision_sequence: 1 }); expect(await counts(ids.dismissed)).toEqual({ decisions: 1, links: 0, events: 1, version: 3 });
      const correction = await executor.execute(principal(), input(ids.suggestion, { expectedVersion: 3, state: "dismissed", idempotencyKey: "correct-dismissal", correctionReason: "wrong match" })); expect(correction).toMatchObject({ status: "decided", sequence: 2, predecessorSequence: 1, version: 4 }); const reconfirmed = await executor.execute(principal(), input(ids.suggestion, { expectedVersion: 4, idempotencyKey: "correct-confirmation", correctionReason: "reviewed again" })); expect(reconfirmed).toMatchObject({ status: "decided", sequence: 3, predecessorSequence: 2, version: 5 }); expect(await state(ids.suggestion)).toEqual({ state: "confirmed", decision_sequence: 3 }); expect(await counts(ids.suggestion)).toEqual({ decisions: 3, links: 1, events: 3, version: 5 });
      const beforeRejected = await counts(ids.suggestion); await expect(executor.execute(principal(), input(ids.suggestion, { expectedVersion: 5, state: "dismissed", idempotencyKey: "missing-reason" }))).rejects.toThrow(RecurrenceDecisionValidationError); await expect(executor.execute(principal(ids.viewer), input(ids.suggestion, { expectedVersion: 5, state: "dismissed", idempotencyKey: "viewer", correctionReason: "no authority" }))).rejects.toThrow("recurrence-decision-forbidden"); await expect(executor.execute(principal(), input(id(23), { expectedVersion: 5, idempotencyKey: "hidden" }))).rejects.toThrow("not-found"); expect(await counts(ids.suggestion)).toEqual(beforeRejected);
      const concurrent = await Promise.allSettled([executor.execute(principal(), input(ids.concurrent, { idempotencyKey: "concurrent-confirm" })), executor.execute(principal(), input(ids.concurrent, { state: "dismissed", idempotencyKey: "concurrent-dismiss" }))]); expect(concurrent.filter((result) => result.status === "fulfilled")).toHaveLength(1); expect(concurrent.filter((result) => result.status === "rejected")).toHaveLength(1); expect(concurrent.find((result) => result.status === "rejected")).toMatchObject({ reason: { message: "stale-version" } }); expect(await counts(ids.concurrent)).toMatchObject({ decisions: 1, events: 1, version: 2 });
      await pool.query("CREATE FUNCTION reject_recurrence_event() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'event rejected'; END $$; CREATE TRIGGER reject_recurrence_event BEFORE INSERT ON incident_events FOR EACH ROW EXECUTE FUNCTION reject_recurrence_event()"); await expect(executor.execute(principal(), input(ids.rollback, { idempotencyKey: "rollback" }))).rejects.toThrow("event rejected"); await pool.query("DROP TRIGGER reject_recurrence_event ON incident_events"); expect(await counts(ids.rollback)).toEqual({ decisions: 0, links: 0, events: 0, version: 1 }); expect(await state(ids.rollback)).toEqual({ state: "pending", decision_sequence: null });
      const uncertain = await new PostgresRecurrenceAuthorityExecutor(lostCommit(pool)).execute(principal(), input(ids.rollback, { idempotencyKey: "lost-commit", correlationId: "lost-correlation" })); expect(uncertain).toEqual({ status: "indeterminate", correlationId: "lost-correlation", retryWithSameKey: true }); await expect(executor.execute(principal(), input(ids.rollback, { idempotencyKey: "lost-commit", correlationId: "lost-correlation" }))).resolves.toMatchObject({ status: "decided", sequence: 1, version: 2 }); expect(await counts(ids.rollback)).toEqual({ decisions: 1, links: 1, events: 1, version: 2 });
    } finally { await pool.end(); await container.stop(); }
  }, 120_000);
});
