import { readFile } from "node:fs/promises";
import { PostgreSqlContainer } from "@testcontainers/postgresql";
import type { Client } from "pg";
import { describe, expect, it } from "vitest";
import { connectReadyPostgres } from "./postgres-test-readiness.js";

const image = "postgres:16.10-alpine@sha256:029660641a0cfc575b14f336ba448fb8a75fd595d42e1fa316b9fb4378742297";
const id = (value: number) => `00000000-0000-7000-8000-${String(value).padStart(12, "0")}`;
const ids = { organization: id(1), store: id(2), sector: id(3), location: id(4), product: id(5), reporter: id(6), actor: id(7), candidate: id(8), incident: id(9), laterIncident: id(10), suggestion: id(11), confirmed: id(12), dismissed: id(13), link: id(14) };
const insertIncident = (client: Client, incidentId: string, title: string) => client.query("INSERT INTO incidents(id,organization_id,store_id,sector_id,location_id,product_id,category_key,severity_key,title,description,occurred_at,reporter_user_id) VALUES($1,$2,$3,$4,$5,$6,'out-of-stock','high',$7,'Description','2026-08-01T10:00:00.000Z',$8)", [incidentId, ids.organization, ids.store, ids.sector, ids.location, ids.product, title, ids.reporter]);

describe("recurrence authority schema", () => {
  it("backfills rule provenance and derives immutable suggestion state without using generic events", async () => {
    let container: Awaited<ReturnType<PostgreSqlContainer["start"]>> | undefined; let client: Client | undefined;
    try {
      container = await new PostgreSqlContainer(image).withDatabase("recurrence_authority").start(); client = await connectReadyPostgres(container.getConnectionUri());
      for (const migration of ["001_reference-data.sql", "005_incidents-core.sql", "006_team-assignments.sql", "007_incident-creation.sql", "008_sla-policy-and-cycles.sql", "009_sla-policy-configuration.sql"]) await client.query(await readFile(`migrations/${migration}`, "utf8"));
      await client.query("INSERT INTO stores(id,organization_id,name) VALUES($1,$2,'A')", [ids.store, ids.organization]); await client.query("INSERT INTO sectors(id,organization_id,store_id,name) VALUES($1,$2,$3,'S')", [ids.sector, ids.organization, ids.store]); await client.query("INSERT INTO locations(id,organization_id,store_id,sector_id,name) VALUES($1,$2,$3,$4,'L')", [ids.location, ids.organization, ids.store, ids.sector]); await client.query("INSERT INTO products(id,organization_id,name) VALUES($1,$2,'P')", [ids.product, ids.organization]); await client.query("INSERT INTO users(id,organization_id,name) VALUES($1,$2,'Reporter'),($3,$2,'Actor')", [ids.reporter, ids.organization, ids.actor]); await insertIncident(client, ids.candidate, "Earlier"); await insertIncident(client, ids.incident, "Current");
      await client.query(await readFile("migrations/010_recurrence-authority.sql", "utf8")); await insertIncident(client, ids.laterIncident, "Later");
      expect((await client.query<{ version: number; window_days: number; maximum_suggestions: number; count: number }>("SELECT r.version,r.window_days,r.maximum_suggestions,count(*)::int count FROM incidents i JOIN recurrence_rule_versions r ON r.id=i.recurrence_rule_version_id AND r.organization_id=i.organization_id GROUP BY r.version,r.window_days,r.maximum_suggestions")).rows).toEqual([{ version: 1, window_days: 30, maximum_suggestions: 5, count: 3 }]);
      const rule = (await client.query<{ id: string }>("SELECT id FROM recurrence_rule_versions WHERE organization_id=$1", [ids.organization])).rows[0]!;
      await client.query("INSERT INTO recurrence_suggestions(id,organization_id,incident_id,candidate_incident_id,recurrence_rule_version_id,occurrence,matching_facts,correlation_id) VALUES($1,$2,$3,$4,$5,1,$6,$7)", [ids.suggestion, ids.organization, ids.incident, ids.candidate, rule.id, JSON.stringify({ locationId: ids.location }), "evaluation-a"]);
      await client.query("INSERT INTO incident_events(id,incident_id,sequence,event_type,actor_user_id,origin) VALUES($1,$2,1,'recurrence-suggested',$3,'system')", [id(15), ids.incident, ids.actor]); await client.query("INSERT INTO incident_events(id,incident_id,sequence,event_type,actor_user_id) VALUES($1,$2,1,'created',$3)", [id(16), ids.candidate, ids.actor]);
      expect((await client.query("SELECT state,decision_sequence,matching_facts FROM current_recurrence_suggestion_states WHERE suggestion_id=$1", [ids.suggestion])).rows).toEqual([{ state: "pending", decision_sequence: null, matching_facts: { locationId: ids.location } }]);
      await client.query("INSERT INTO recurrence_decisions(id,organization_id,suggestion_id,sequence,state,actor_user_id,note,correlation_id) VALUES($1,$2,$3,1,'confirmed',$4,'Confirmed','decision-a')", [ids.confirmed, ids.organization, ids.suggestion, ids.actor]); await client.query("INSERT INTO recurrence_links(id,organization_id,suggestion_id,confirmed_decision_id) VALUES($1,$2,$3,$4)", [ids.link, ids.organization, ids.suggestion, ids.confirmed]);
      expect((await client.query("SELECT state,decision_sequence FROM current_recurrence_suggestion_states WHERE suggestion_id=$1", [ids.suggestion])).rows).toEqual([{ state: "confirmed", decision_sequence: 1 }]);
      await expect(client.query("INSERT INTO recurrence_decisions(id,organization_id,suggestion_id,sequence,state,actor_user_id,correction_reason,predecessor_sequence,correlation_id) VALUES($1,$2,$3,2,'pending',$4,'Reason',1,'invalid')", [id(17), ids.organization, ids.suggestion, ids.actor])).rejects.toThrow();
      await client.query("INSERT INTO recurrence_decisions(id,organization_id,suggestion_id,sequence,state,actor_user_id,correction_reason,predecessor_sequence,correlation_id) VALUES($1,$2,$3,2,'dismissed',$4,'Incorrect match',1,'decision-b')", [ids.dismissed, ids.organization, ids.suggestion, ids.actor]);
      expect((await client.query("SELECT state,decision_sequence FROM current_recurrence_suggestion_states WHERE suggestion_id=$1", [ids.suggestion])).rows).toEqual([{ state: "dismissed", decision_sequence: 2 }]);
      await expect(client.query("UPDATE recurrence_suggestions SET version=2 WHERE id=$1", [ids.suggestion])).rejects.toThrow("recurrence authority is immutable"); await expect(client.query("DELETE FROM recurrence_decisions WHERE id=$1", [ids.dismissed])).rejects.toThrow("recurrence authority is immutable"); await expect(client.query("UPDATE incident_events SET origin='robot' WHERE id=$1", [id(15)])).rejects.toThrow();
      expect((await client.query<{ indexname: string }>("SELECT indexname FROM pg_indexes WHERE tablename IN ('recurrence_suggestions','recurrence_decisions') ORDER BY indexname")).rows.map(({ indexname }) => indexname)).toEqual(expect.arrayContaining(["recurrence_decisions_current_idx", "recurrence_suggestions_owner_created_idx"]));
    } finally { try { await client?.end(); } finally { await container?.stop(); } }
  }, 120_000);
});
