import { readFile } from "node:fs/promises";
import { PostgreSqlContainer } from "@testcontainers/postgresql";
import { Client } from "pg";
import { describe, expect, it } from "vitest";

const image = "postgres:16.10-alpine@sha256:029660641a0cfc575b14f336ba448fb8a75fd595d42e1fa316b9fb4378742297";
const id = (value: number) => `00000000-0000-7000-8000-${String(value).padStart(12, "0")}`;
const ids = { organization: id(1), store: id(101), sector: id(102), location: id(103), product: id(104), actor: id(105), assignee: id(106), incident: id(107), otherIncident: id(108), snapshot: id(109), otherSnapshot: id(110), cycle: id(111), closedSegment: id(112), activeSegment: id(113), evaluation: id(114), decisionSet: id(115), categoryDecision: id(116), assigneeDecision: id(117), replacementSnapshot: id(118), replacementSegment: id(119) };
const migrations = ["001_reference-data.sql", "002_identity-sessions.sql", "003_configuration-events.sql", "004_reference-configuration-idempotency.sql", "005_incidents-core.sql", "006_team-assignments.sql", "007_incident-creation.sql", "008_sla-policy-and-cycles.sql", "009_sla-policy-configuration.sql", "010_recurrence-authority.sql"];
const insertIncident = (client: Client, incidentId: string, title: string) => client.query("INSERT INTO incidents(id,organization_id,store_id,sector_id,location_id,product_id,category_key,severity_key,title,description,occurred_at,reporter_user_id) VALUES($1,$2,$3,$4,$5,$6,'out-of-stock','high',$7,'Description','2026-08-01T10:00:00.000Z',$8)", [incidentId, ids.organization, ids.store, ids.sector, ids.location, ids.product, title, ids.actor]);
const insertSnapshot = (client: Client, snapshotId: string, incidentId: string) => client.query("INSERT INTO incident_sla_rule_snapshots(id,incident_id,organization_id,policy_version_id,policy_version,category_key,severity_key,clock_mode,pauses_when_blocked,warning_after_seconds,deadline_after_seconds) VALUES($1,$2,$3,$3,1,'out-of-stock','high','continuous-utc',false,14400,28800)", [snapshotId, incidentId, ids.organization]);

describe("triage migration schema", () => {
  it("preserves prior migration data while constraining immutable triage and SLA history", async () => {
    let container: Awaited<ReturnType<PostgreSqlContainer["start"]>> | undefined; let client: Client | undefined;
    try {
      container = await new PostgreSqlContainer(image).withDatabase("triage_schema").start(); client = new Client({ connectionString: container.getConnectionUri() }); await client.connect();
      for (const migration of migrations) await client.query(await readFile(`migrations/${migration}`, "utf8"));
      await client.query("INSERT INTO stores(id,organization_id,name) VALUES($1,$2,'Store')", [ids.store, ids.organization]); await client.query("INSERT INTO sectors(id,organization_id,store_id,name) VALUES($1,$2,$3,'Sector')", [ids.sector, ids.organization, ids.store]); await client.query("INSERT INTO locations(id,organization_id,store_id,sector_id,name) VALUES($1,$2,$3,$4,'Location')", [ids.location, ids.organization, ids.store, ids.sector]); await client.query("INSERT INTO products(id,organization_id,name) VALUES($1,$2,'Product')", [ids.product, ids.organization]); await client.query("INSERT INTO users(id,organization_id,name) VALUES($1,$2,'Actor'),($3,$2,'Assignee')", [ids.actor, ids.organization, ids.assignee]); await insertIncident(client, ids.incident, "Current"); await insertIncident(client, ids.otherIncident, "Other"); await insertSnapshot(client, ids.snapshot, ids.incident); await client.query("INSERT INTO incident_sla_cycles(id,incident_id,snapshot_id,sequence,condition,started_at,warning_at,deadline_at) VALUES($1,$2,$3,1,'on-track','2026-08-01T10:00:00Z','2026-08-01T14:00:00Z','2026-08-01T18:00:00Z')", [ids.cycle, ids.incident, ids.snapshot]); await client.query("INSERT INTO incident_sla_segments(id,cycle_id,snapshot_id,sequence,started_at,warning_at,deadline_at,active) VALUES($1,$2,$3,1,'2026-08-01T10:00:00Z','2026-08-01T14:00:00Z','2026-08-01T18:00:00Z',false),($4,$2,$3,2,'2026-08-01T10:00:00Z','2026-08-01T14:00:00Z','2026-08-01T18:00:00Z',true)", [ids.closedSegment, ids.cycle, ids.snapshot, ids.activeSegment]);
      const migration = await readFile("migrations/011_triage.sql", "utf8").catch(() => ""); if (migration) await client.query(migration);
      expect((await client.query("SELECT v.id version_id,v.version,r.id rule_id,r.identifier,r.priority,r.store_id,r.sector_id,r.location_id,r.product_id,r.category_key,r.severity_key,r.assignee_strategy FROM triage_rule_versions v JOIN triage_rules r ON r.rule_version_id=v.id WHERE v.organization_id=$1", [ids.organization])).rows).toEqual([{ version_id: id(3), version: 1, rule_id: id(4), identifier: "default-catch-all", priority: 1, store_id: null, sector_id: null, location_id: null, product_id: null, category_key: null, severity_key: null, assignee_strategy: "single-eligible" }]);
      expect((await client.query("SELECT bool_and(incident_id=$1) incident_scoped,bool_and((active AND ended_at IS NULL) OR (NOT active AND ended_at IS NOT NULL)) lifecycle_backfilled FROM incident_sla_segments WHERE cycle_id=$2", [ids.incident, ids.cycle])).rows).toEqual([{ incident_scoped: true, lifecycle_backfilled: true }]);
      for (const [ruleId, identifier] of [[id(120), "same-priority-a"], [id(121), "same-priority-b"]] as const) await client.query("INSERT INTO triage_rules(id,organization_id,rule_version_id,identifier,priority,assignee_strategy) VALUES($1,$2,$3,$4,2,'single-eligible')", [ruleId, ids.organization, id(3), identifier]);
      expect((await client.query("SELECT identifier FROM triage_rules WHERE rule_version_id=$1 ORDER BY priority,id", [id(3)])).rows).toEqual([{ identifier: "default-catch-all" }, { identifier: "same-priority-a" }, { identifier: "same-priority-b" }]);
      await client.query("INSERT INTO triage_evaluations(id,organization_id,incident_id,incident_version,rule_version_id,rule_id,rule_identifier,inputs,suggested,explanation,action_correlation_id) VALUES($1,$2,$3,1,$4,$5,'default-catch-all','{}','{}','{}','evaluation-a')", [ids.evaluation, ids.organization, ids.incident, id(3), id(4)]); await client.query("INSERT INTO triage_decision_sets(id,organization_id,incident_id,evaluation_id,sequence,complete,action_correlation_id) VALUES($1,$2,$3,$4,1,false,'decision-a')", [ids.decisionSet, ids.organization, ids.incident, ids.evaluation]); await client.query("INSERT INTO triage_decision_items(id,organization_id,decision_set_id,field,disposition,value_text,value_user_id,actor_user_id,action_correlation_id) VALUES($1,$2,$3,'category','confirmed','out-of-stock',NULL,$4,'decision-a'),($5,$2,$3,'assignee','manual',NULL,$6,$6,'decision-a')", [ids.categoryDecision, ids.organization, ids.decisionSet, ids.actor, ids.assigneeDecision, ids.assignee]); await client.query("INSERT INTO triage_idempotency_outcomes(organization_id,principal_id,api_major,action,incident_id,key,request_hash,outcome,action_correlation_id) VALUES($1,$2,'v1','triage-evaluate',$3,'key-a','hash-a','{}','evaluation-a')", [ids.organization, ids.actor, ids.incident]); expect((await client.query("SELECT completed_at IS NOT NULL completed FROM triage_idempotency_outcomes")).rows).toEqual([{ completed: true }]);
      const reject = (sql: string, values: unknown[] = []) => expect(client!.query(sql, values)).rejects.toThrow();
      await reject("INSERT INTO triage_rules(id,organization_id,rule_version_id,identifier,priority,assignee_strategy) VALUES($1,$2,$3,'invalid-priority',0,'single-eligible')", [id(122), ids.organization, id(3)]); await reject("INSERT INTO triage_evaluations(id,organization_id,incident_id,incident_version,rule_version_id,rule_id,rule_identifier,inputs,suggested,explanation,action_correlation_id) VALUES($1,$2,$3,0,$4,$5,'default-catch-all','{}','{}','{}','invalid')", [id(123), ids.organization, ids.incident, id(3), id(4)]); await reject("INSERT INTO triage_evaluations(id,organization_id,incident_id,incident_version,rule_version_id,rule_id,rule_identifier,inputs,suggested,explanation,action_correlation_id) VALUES($1,$2,$3,1,$4,$5,'default-catch-all','{}','{}','{}','duplicate')", [id(124), ids.organization, ids.incident, id(3), id(4)]); await reject("INSERT INTO triage_decision_sets(id,organization_id,incident_id,evaluation_id,sequence,complete,action_correlation_id) VALUES($1,$2,$3,$4,0,false,'invalid')", [id(125), ids.organization, ids.incident, ids.evaluation]); await reject("INSERT INTO triage_decision_sets(id,organization_id,incident_id,evaluation_id,sequence,complete,action_correlation_id) VALUES($1,$2,$3,$4,1,false,'duplicate')", [id(126), ids.organization, ids.incident, ids.evaluation]);
      await reject("INSERT INTO triage_evaluations(id,organization_id,incident_id,incident_version,rule_version_id,rule_id,rule_identifier,inputs,suggested,explanation,action_correlation_id) VALUES($1,$2,$3,2,$4,$5,'default-catch-all','{}','{}','{}','invalid')", [id(126), id(999), ids.incident, id(3), id(4)]); await reject("INSERT INTO triage_decision_sets(id,organization_id,incident_id,evaluation_id,sequence,complete,action_correlation_id) VALUES($1,$2,$3,$4,2,false,'cross-incident')", [id(127), ids.organization, ids.otherIncident, ids.evaluation]); await reject("INSERT INTO triage_decision_items(id,organization_id,decision_set_id,field,disposition,value_user_id,actor_user_id,action_correlation_id) VALUES($1,$2,$3,'category','confirmed',$4,$4,'invalid')", [id(128), ids.organization, ids.decisionSet, ids.assignee]); await reject("INSERT INTO triage_decision_items(id,organization_id,decision_set_id,field,disposition,value_text,actor_user_id,action_correlation_id) VALUES($1,$2,$3,'assignee','manual','not-a-user',$4,'invalid')", [id(129), ids.organization, ids.decisionSet, ids.actor]); await reject("INSERT INTO triage_decision_items(id,organization_id,decision_set_id,field,disposition,value_text,actor_user_id,action_correlation_id) VALUES($1,$2,$3,'category','confirmed','other',$4,'duplicate')", [id(130), ids.organization, ids.decisionSet, ids.actor]); await reject("INSERT INTO triage_idempotency_outcomes(organization_id,principal_id,api_major,action,incident_id,key,request_hash,outcome,action_correlation_id) VALUES($1,$2,'v1','triage-evaluate',$3,'key-a','hash-b','{}','evaluation-b')", [ids.organization, ids.actor, ids.incident]);
      for (const [sql, values] of [["UPDATE triage_rule_versions SET version=2 WHERE id='00000000-0000-7000-8000-000000000003'", []], ["DELETE FROM triage_rules WHERE id='00000000-0000-7000-8000-000000000004'", []], ["UPDATE triage_evaluations SET incident_version=2 WHERE id=$1", [ids.evaluation]], ["DELETE FROM triage_decision_sets WHERE id=$1", [ids.decisionSet]], ["UPDATE triage_decision_items SET value_text='changed' WHERE id=$1", [ids.categoryDecision]], ["UPDATE triage_idempotency_outcomes SET request_hash='changed' WHERE organization_id=$1", [ids.organization]], ["DELETE FROM triage_idempotency_outcomes WHERE organization_id=$1", [ids.organization]]] as const) await reject(sql, [...values]);
      await reject("UPDATE incident_sla_segments SET warning_at='2026-08-01T15:00:00Z' WHERE id=$1", [ids.activeSegment]); await reject("UPDATE incident_sla_segments SET active=false WHERE id=$1", [ids.activeSegment]); await client.query("UPDATE incident_sla_segments SET active=false,ended_at='2026-08-01T16:00:00Z' WHERE id=$1", [ids.activeSegment]); await reject("UPDATE incident_sla_segments SET active=false WHERE id=$1", [ids.activeSegment]); await reject("UPDATE incident_sla_segments SET ended_at='2026-08-01T17:00:00Z' WHERE id=$1", [ids.activeSegment]); await reject("DELETE FROM incident_sla_segments WHERE id=$1", [ids.activeSegment]);
      await insertSnapshot(client, ids.replacementSnapshot, ids.incident); await client.query("INSERT INTO incident_sla_segments(id,cycle_id,snapshot_id,incident_id,sequence,started_at,warning_at,deadline_at,active) VALUES($1,$2,$3,$4,3,'2026-08-01T16:00:00Z','2026-08-01T20:00:00Z','2026-08-02T00:00:00Z',true)", [ids.replacementSegment, ids.cycle, ids.replacementSnapshot, ids.incident]); await insertSnapshot(client, ids.otherSnapshot, ids.otherIncident); await reject("INSERT INTO incident_sla_segments(id,cycle_id,snapshot_id,incident_id,sequence,started_at,warning_at,deadline_at,active) VALUES($1,$2,$3,$4,4,'2026-08-01T16:00:00Z','2026-08-01T20:00:00Z','2026-08-02T00:00:00Z',true)", [id(131), ids.cycle, ids.otherSnapshot, ids.incident]);
      expect((await client.query("SELECT snapshot_id FROM incident_sla_segments WHERE id=$1", [ids.replacementSegment])).rows).toEqual([{ snapshot_id: ids.replacementSnapshot }]);
    } finally { try { await client?.end(); } finally { await container?.stop(); } }
  }, 120_000);
});
