variable "name" {
  description = "Name prefix for every resource in this module."
  type        = string
}

variable "vpc_id" {
  description = "VPC that owns the database security group."
  type        = string
}

variable "private_subnet_ids" {
  description = "Private subnet identifiers for the DB subnet group."
  type        = list(string)
}

variable "task_security_group_id" {
  description = "Application task security group allowed to reach PostgreSQL."
  type        = string
}

variable "instance_class" {
  description = "RDS instance class."
  type        = string
  default     = "db.t4g.micro"
}

variable "engine_version" {
  description = "PostgreSQL engine version (major is enough; RDS selects the latest minor)."
  type        = string
  default     = "16"
}

variable "database_name" {
  description = "Initial database name."
  type        = string
  default     = "shelfops"
}

variable "username" {
  description = "Master username."
  type        = string
  default     = "shelfops"
}

variable "password" {
  description = "Master password. Generated by the caller and stored in Secrets Manager."
  type        = string
  sensitive   = true
}

variable "ca_cert_identifier" {
  description = "RDS certificate authority. Must be present in the bundled global-bundle.pem."
  type        = string
  default     = "rds-ca-rsa2048-g1"
}

variable "backup_retention_days" {
  description = "Automated backup retention in days (0 disables backups)."
  type        = number
  default     = 1
}

variable "deletion_protection" {
  description = "Enable RDS deletion protection. False for the ephemeral demo."
  type        = bool
  default     = false
}

variable "skip_final_snapshot" {
  description = "Skip the final snapshot on destroy. True for the ephemeral demo."
  type        = bool
  default     = true
}
